# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run gofmt
        run: |
          output=$(gofmt -l .)
          if [ -n "$output" ]; then
            echo "The following files are not properly formatted:"
            echo "$output"
            exit 1
          fi

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -v ./...
